version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/teacher_webapp
    ports:
      - 8001:80
    environment:
      - DATABASE_URL=sqlite:///test.db