# Generated by Django 5.0.4 on 2024-06-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='main_teacher_id',
            new_name='main_teacher',
        ),
    ]
