# Generated by Django 5.0.4 on 2024-06-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='ClassYear',
        ),
        migrations.RenameField(
            model_name='classyear',
            old_name='grade',
            new_name='classYear',
        ),
    ]
