# Generated by Django 5.0.4 on 2024-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='health_group',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
