# Generated by Django 5.0.4 on 2024-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_olympiads_info_alter_olympiads_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiads',
            name='place',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
