# Generated by Django 5.0.4 on 2024-06-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_main_teacher_id_classes_main_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassYear',
        ),
    ]
