# Generated by Django 5.0.4 on 2024-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_health_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='health_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
