# Generated by Django 5.0.4 on 2024-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiads',
            name='info',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='olympiads',
            name='place',
            field=models.CharField(max_length=512),
        ),
    ]
