version: '3'

services:
  web:
    build: .
    env_file:
      - ./teacher_webapp/.env
    command: gunicorn teacher_webapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app

  nginx:
    image: nginx:latest
    env_file:
      - ./teacher_webapp/.env
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static
      - ./media:/app/media
    depends_on:
      - web
